[package]
name = "is_generic"
version = "0.1.0"
edition = "2021"
description = "A trait to search for generic types in syntax trees"
license = "MIT OR Apache-2.0"

[dependencies]
syn = { version = "2.0", features = ["full"] }
